---
title: "Genetic algorithms training"
author: "José Alberto Arcos Sánchez"
date: "15 de octubre de 2015"
output: html_document
---

Chromosome definition:

{LIFSOR}

- L >> number of layers in the neural network, including input and output layers
- I >> number of neurons in the input layer
- F >> number of neurons in the first hidden layer
- S >> number of neurons in the second hidden layer
- O >> number of neurons in the output layer
- R >> regularization factor

Maximal and minimal values:

- 1 < L < 4 
- 0 < I < Inf
- 0 < F < Inf
- 0 < S < Inf
- 0 < O < Inf
- 0 <= R < Inf

```{r}
library(genalg)

min.values <- c(1, 0, 0, 0, 0, 0)
max.values <- c(4, 1000, 1000, 1000, 1000, 1000)

evaluation <- function(chromosome){
    sum(chromosome)
}

rbga(stringMin = min.values,
     stringMax = max.values,
     suggestions = NULL,
     popSize = 50,
     iters = 1000,
     elitism = 2,
     mutationChance = 0.5,
     showSettings = TRUE,
     verbose = TRUE,
     evalFunc = evaluation) -> model

model

```


```{r}

```


```{r}

```